Repository Final-Earth-Stuff/Skynet-Rewrite, pull requests merged in 2022-07, with the labels that each got.

#119 Fix bug with verify-all
  src/handler/guild/verifyAll.ts
  src/service/nickname.ts
Labels: bugfix

#120 fixed verify messages arriving out of order
  src/handler/guild/verifyAll.ts
Labels: bugfix

#122 Adjust log levels to reduce spam in the console log
  src/bot.ts
  src/handler/job/monitorRanks.ts
  src/handler/job/monitorUsers.ts
  src/handler/job/monitorWorld.ts
  src/logger.ts
Labels: refactor

#123 Fix auto verify
  src/handler/job/monitorRanks.ts
  src/service/nicknameService.ts
  src/service/verifyService.ts
Labels: bugfix

#124 fix crash in `monitorUsers` job
  src/handler/job/monitorUsers.ts
Labels: bugfix

#126 Migrate to discordjs v14
  package.json
  src/bot.ts
  src/config.ts
  src/decorators/CommandHandler.ts
  src/decorators/EventHandler.ts
  src/decorators/index.ts
  src/handler/global/delete.ts
  src/handler/global/dis.ts
  src/handler/global/factories.ts
  src/handler/global/help.ts
  src/handler/global/mines.ts
  src/handler/global/nuke.ts
  src/handler/global/personalstats.ts
  src/handler/global/prox.ts
  src/handler/global/region.ts
  src/handler/global/remind.ts
  src/handler/global/rigs.ts
  src/handler/global/settings.ts
  src/handler/global/spawns.ts
  src/handler/global/start.ts
  src/handler/global/totals.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/handler/job/monitorRanks.ts
  src/handler/job/monitorReminders.ts
  src/handler/job/monitorUsers.ts
  src/handler/job/monitorWorld.ts
  src/handler/util/countryComplete.ts
  src/logger.ts
  src/map/index.ts
  src/scripts/updateCommands.ts
  src/scripts/updateStaticData.ts
  src/service/facilitiesChanges.ts
  src/service/mapCommands.ts
  src/service/nicknameService.ts
  src/service/reminders.ts
  src/service/troopMovements.ts
  src/service/util/constants.ts
  src/service/verifyService.ts
  src/util/assert.ts
  src/wrapper/wrapper.ts
  tsconfig.json
  yarn.lock
Labels: refactor

#127 added API JSON validation using io-ts
  package.json
  src/handler/global/personalstats.ts
  src/handler/global/start.ts
  src/wrapper/models/allunits.ts
  src/wrapper/models/common.ts
  src/wrapper/models/country.ts
  src/wrapper/models/formation.ts
  src/wrapper/models/notification.ts
  src/wrapper/models/units.ts
  src/wrapper/models/user.ts
  src/wrapper/wrapper.ts
  yarn.lock
Labels: refactor

#128 update dependencies
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarnrc.yml
  package.json
  src/handler/util/countryComplete.ts
  yarn.lock
Labels: chore

#129 fix notifications typings in order to account for inconsistency in the api
  src/wrapper/models/notification.ts
Labels: bug
