Repository Final-Earth-Stuff/Skynet-Rewrite, pull requests merged in 2022-04, with the labels that each got.

#47 workaround for node-cron behaviour for identical cron strings
  src/bot.ts
  src/decorators/ScheduledJob.ts
  src/decorators/data.ts
Labels: bugfix

#54 read country names from db
  src/bot.ts
  src/handler/global/spawns.ts
  src/repository/LandAndFacilitiesRepository.ts
  src/scripts/updateCommands.ts
Labels: phase 1, refactor

#55 fixed event handler types
  src/bot.ts
  src/decorators/EventHandler.ts
  src/decorators/data.ts
Labels: bugfix

#56 Bugfix for real
  src/bot.ts
  src/handler/guild/role.ts
Labels: bugfix

#53 Guards
  src/decorators/Guard.ts
  src/decorators/index.ts
  src/guard/commandChannelGuard.ts
  src/guard/verifyGuard.ts
  src/handler/global/delete.ts
  src/handler/global/dis.ts
  src/handler/global/factories.ts
  src/handler/global/mines.ts
  src/handler/global/nuke.ts
  src/handler/global/prox.ts
  src/handler/global/region.ts
  src/handler/global/remind.ts
  src/handler/global/rigs.ts
  src/handler/global/settings.ts
  src/handler/global/spawns.ts
  src/handler/global/start.ts
  src/handler/global/totals.ts
  src/handler/guild/verify.ts
Labels: phase 1

#58 add build workflow
  .github/workflows/node.js.yml
  package.json
  src/bot.ts
  src/guard/commandChannelGuard.ts
  src/guard/verifyGuard.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  yarn.lock
Labels: chore

#59 refactored map data storage and write derived data to fs
  .gitignore
  src/bot.ts
  src/handler/global/dis.ts
  src/handler/global/nuke.ts
  src/handler/util/countryComplete.ts
  src/map/index.ts
  src/map/kdtree.ts
  src/scripts/updateStaticData.ts
  src/util/assert.ts
Labels: refactor

#60 Totals
  src/handler/global/totals.ts
  src/repository/LandAndFacilitiesRepository.ts
Labels: phase 1

#57 Collect troop movement data and output to channel
  src/entity/UserSettings.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/handler/job/monitorUsers.ts
  src/handler/job/monitorWorld.ts
  src/map/util.ts
  src/repository/UnitChangeRepository.ts
  src/repository/UserSettingsRepository.ts
  src/service/facilitiesChanges.ts
  src/service/troopMovements.ts
  src/service/util/constants.ts
  src/service/util/team.ts
  src/wrapper/models/user.ts
Labels: phase 1

#65 refactored troop movements and hopefully eliminated bugs
  src/entity/UnitChange.ts
  src/handler/global/totals.ts
  src/handler/job/monitorWorld.ts
  src/service/troopMovements.ts
  src/service/util/team.ts
  src/util/assert.ts
  src/util/guard.ts
Labels: bugfix, refactor

#67 upgraded `@discordjs/builders` to resolve conflict with `discord-api-…
  package.json
  yarn.lock
Labels: chore

#70 Log facility changes to channel
  src/handler/job/monitorWorld.ts
  src/service/facilitiesChanges.ts
  src/service/util/constants.ts
Labels: phase 1

#71 implemented /prox
  src/handler/global/prox.ts
  src/map/kdtree.ts
  src/map/util.ts
  src/repository/UnitChangeRepository.ts
Labels: phase 1

#72 Reminder entity and command
  src/entity/Reminder.ts
  src/entity/UserSettings.ts
  src/handler/global/remind.ts
Labels: phase 1

#74 Various fixes for problems that occurred when deploying the bot
  .gitignore
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  package.json
  src/service/facilitiesChanges.ts
  yarn.lock
Labels: bugfix

#77 updated README
  README.md
Labels: chore

#78 Income commands
  src/handler/global/factories.ts
  src/handler/global/mines.ts
  src/handler/global/rigs.ts
  src/repository/LandAndFacilitiesRepository.ts
  src/service/mapCommands.ts
Labels: phase 1

#82 lowered threshold for income commands and added constants
  src/handler/global/factories.ts
  src/handler/global/mines.ts
  src/handler/global/rigs.ts
  src/service/mapCommands.ts
  src/service/util/constants.ts
Labels: refactor

#79 Reminders
  src/handler/job/monitorReminders.ts
  src/repository/ReminderRepository.ts
  src/service/reminders.ts
  src/service/util/constants.ts
Labels: phase 1

#85 Workflow cache
  .github/workflows/node.js.yml
Labels: chore

#84 Refactor typeorm
  package.json
  src/config.ts
  src/datasource.ts
  src/entity/LandAndFacilities.ts
  src/entity/UnitChange.ts
  src/index.ts
  src/migration/1649940846571-AddCompositeIndices.ts
  src/parser.ts
Labels: refactor

#83 use `Color` enum for all embeds
  src/decorators/Button.ts
  src/decorators/Command.ts
  src/handler/global/delete.ts
  src/handler/global/dis.ts
  src/handler/global/nuke.ts
  src/handler/global/region.ts
  src/handler/global/spawns.ts
  src/handler/global/start.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/service/util/constants.ts
Labels: refactor

#86 Track user rank and update nickname accordingly
  src/bot.ts
  src/entity/RankRole.ts
  src/entity/UserRank.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/handler/job/monitorRanks.ts
  src/repository/UserRankRepository.ts
  src/service/nickname.ts
  src/service/util/constants.ts
Labels: phase 2

#87 Refactor settings command
  src/guard/dmGuard.ts
  src/handler/global/delete.ts
  src/handler/global/remind.ts
  src/handler/global/settings.ts
  src/handler/global/start.ts
  src/service/util/constants.ts
Labels: refactor
