Repository Final-Earth-Stuff/Skynet-Rewrite, pull requests merged in 2022-06, with the labels that each got.

#101 Make start command errors ephemeral to prevent api key leaks
  src/guard/dmGuard.ts
  src/handler/global/personalstats.ts
  src/handler/global/settings.ts
  src/handler/global/start.ts
Labels: bugfix

#106 Refactor decorators
  package.json
  src/bot.ts
  src/decorators/AfterCommandUpdate.ts
  src/decorators/BaseScope.ts
  src/decorators/Button.ts
  src/decorators/Command.ts
  src/decorators/CommandData.ts
  src/decorators/CommandHandler.ts
  src/decorators/Completion.ts
  src/decorators/EventHandler.ts
  src/decorators/Guard.ts
  src/decorators/ScheduledJob.ts
  src/decorators/data.ts
  src/decorators/index.ts
  src/handler/global/delete.ts
  src/handler/global/dis.ts
  src/handler/global/factories.ts
  src/handler/global/mines.ts
  src/handler/global/nuke.ts
  src/handler/global/personalstats.ts
  src/handler/global/prox.ts
  src/handler/global/region.ts
  src/handler/global/remind.ts
  src/handler/global/rigs.ts
  src/handler/global/settings.ts
  src/handler/global/spawns.ts
  src/handler/global/start.ts
  src/handler/global/totals.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/handler/job/monitorRanks.ts
  src/handler/job/monitorReminders.ts
  src/handler/job/monitorUsers.ts
  src/handler/job/monitorWorld.ts
  src/handler/util/countryComplete.ts
  src/scripts/updateCommands.ts
  src/service/verifyService.ts
  yarn.lock
Labels: refactor

#111 Restrict Permissions on admin commands automatically
  package.json
  src/decorators/CommandHandler.ts
  src/decorators/Completion.ts
  src/entity/Guild.ts
  src/handler/global/nuke.ts
  src/handler/global/prox.ts
  src/handler/global/region.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/handler/guild/verifyAll.ts
  src/handler/util/countryComplete.ts
  yarn.lock
Labels: enhancement

#112 Fixes bugs with /prox resolves #89, #109 and #110
  src/handler/global/prox.ts
  src/map/kdtree.ts
  src/repository/UnitChangeRepository.ts
Labels: bugfix

#113 Add help command and restrict notifcation commands to DMs
  src/guard/dmGuard.ts
  src/handler/global/delete.ts
  src/handler/global/help.ts
  src/handler/global/remind.ts
  src/handler/global/settings.ts
  src/handler/global/start.ts
Labels: enhancement, refactor

#108 add default values for map queries
  src/handler/global/dis.ts
  src/handler/global/factories.ts
  src/handler/global/mines.ts
  src/handler/global/nuke.ts
  src/handler/global/personalstats.ts
  src/handler/global/prox.ts
  src/handler/global/region.ts
  src/handler/global/rigs.ts
  src/handler/global/spawns.ts
  src/handler/global/totals.ts
  src/handler/guild/channel.ts
  src/handler/guild/role.ts
  src/repository/LandAndFacilitiesRepository.ts
Labels: bugfix

#118 added totals to /spawns
  package.json
  src/handler/global/spawns.ts
  yarn.lock
Labels: enhancement
