Repository Final-Earth-Stuff/Skynet-Rewrite, pull requests merged in 2022-08, with the labels that each got.

#132 widen snowflakes and add verified role
  .eslintrc
  package.json
  src/datasource.ts
  src/entity/Command.ts
  src/entity/Guild.ts
  src/entity/RankRole.ts
  src/entity/UserRank.ts
  src/entity/UserSettings.ts
  src/handler/guild/role.ts
  src/map/kdtree.ts
  src/migration/1661184309284-migration.ts
  src/service/verifyService.ts
  src/wrapper/wrapper.ts
Labels: enhancement, bugfix

#134 fixed linter warnings
  .eslintrc
  package.json
  src/bot.ts
  src/decorators/BaseScope.ts
  src/decorators/Button.ts
  src/decorators/CommandHandler.ts
  src/decorators/Completion.ts
  src/decorators/EventHandler.ts
  src/decorators/ScheduledJob.ts
  src/decorators/index.ts
  src/guard/verifyGuard.ts
  src/handler/global/delete.ts
  src/handler/global/dis.ts
  src/handler/global/nuke.ts
  src/handler/global/personalstats.ts
  src/handler/global/remind.ts
  src/handler/global/settings.ts
  src/handler/global/spawns.ts
  src/handler/global/start.ts
  src/handler/job/monitorRanks.ts
  src/handler/job/monitorReminders.ts
  src/handler/job/monitorUsers.ts
  src/handler/job/monitorWorld.ts
  src/handler/util/countryComplete.ts
  src/index.ts
  src/logger.ts
  src/map/index.ts
  src/repository/CommandRepository.ts
  src/repository/LandAndFacilitiesRepository.ts
  src/repository/UnitChangeRepository.ts
  src/service/facilitiesChanges.ts
  src/service/mapCommands.ts
  src/service/nicknameService.ts
  src/service/reminders.ts
  src/service/troopMovements.ts
  src/service/util/constants.ts
  src/service/verifyService.ts
  src/wrapper/wrapper.ts
  tsconfig.json
  yarn.lock
Labels: bugfix, refactor

#135 fix snowflake column type
  package.json
  src/entity/Command.ts
  src/entity/Guild.ts
  src/entity/RankRole.ts
  src/entity/UserRank.ts
  src/entity/UserSettings.ts
  src/migration/1661197681503-migration.ts
Labels: bugfix

#136 updated dependencies
  package.json
  yarn.lock
Labels: chore

#137 combined nickname and role updates
  src/handler/guild/verify.ts
  src/handler/guild/verifyAll.ts
  src/repository/UserRankRepository.ts
  src/service/nicknameService.ts
  src/service/verifyService.ts
Labels: enhancement, bugfix

#138 fix bug that removed spectator role in between rounds
  src/service/verifyService.ts
Labels: bugfix

#140 Add admin command to toggle team role setting
  src/entity/Guild.ts
  src/handler/guild/role.ts
  src/migration/1661354809556-migration.ts
  src/service/verifyService.ts
Labels: enhancement

#141 Add auto role
  src/entity/Guild.ts
  src/handler/guild/role.ts
  src/service/verifyService.ts
Labels: enhancement

#139 Add age personal stat and fix points bug
  src/handler/global/personalstats.ts
Labels: enhancement, bugfix

#144 remove auto and spectator roles when verifying
  src/service/verifyService.ts
Labels: bugfix

#145 handle case that user left guild
  src/handler/job/monitorRanks.ts
  src/service/verifyService.ts
Labels: bugfix

#146 fix country model
  src/handler/job/monitorUsers.ts
  src/repository/UserSettingsRepository.ts
  src/wrapper/wrapper.ts
Labels: bugfix

#147 /Route
  .github/workflows/node.js.yml
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.1.1.cjs
  .yarn/releases/yarn-3.2.3.cjs
  .yarnrc.yml
  README.md
  helpers/.gitignore
  helpers/.npmignore
  helpers/.yarnrc.yml
  helpers/Cargo.toml
  helpers/build.rs
  helpers/package.json
  helpers/rustfmt.toml
  helpers/src/engine.rs
  helpers/src/lib.rs
  helpers/src/model.rs
  package.json
  src/handler/global/personalstats.ts
  src/handler/global/prox.ts
  src/handler/global/route.ts
  src/map/geometry.ts
  src/map/index.ts
  src/map/kdtree.ts
  yarn.lock
Labels: enhancement
